name: pre-commit

on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.7'
      - name: install deps
        run: pip install flake8 black

      - name: black
        run: black --check maggy

      - name: flake8
        run: flake8 maggy
